### ISSUE TITLE
Support Arnold 5.1.0.0

### ISSUE THREAD

**Issue by caron** [Autodesk/sitoa#2]
Lots of new stuff to support...

https://support.solidangle.com/display/A5ARP/5.1.0.0

First ticket to start tracking these changes.

**Comment by JenusL** [comment]
That is indeed a lot of new stuff. Awesome!
New MtoA is just released as well with a major version bump to v3.0.0.
I hope I'll have some time to dig in to this soon.

**Comment by JenusL** [comment]
I started with this yesterday and you can follow along here: [JenusL/sitoa/devel](https://github.com/JenusL/sitoa/tree/devel)

**Comment by kikou** [comment]
Nice! Please break you changes down in smaller chunks and create pull requests that we can easily review and accept.

**Comment by JenusL** [comment]
@kikou I'm trying to :)

**Comment by JenusL** [comment]
So I've made a start with PR #4 #5 and #6.
This passes the testsuite so it should be safe to use.
However, there are right now 3 warnings when you render.
`// WARNING : [arnold] unable to load dynamic library <my_local_git_path>\Softimage_2015_SP2\Addons\SItoA\Application\Plugins\bin\nt-x86-64\optix_denoiser.dll: The specified module could not be found.
//// WARNING : [arnold] cannot declare constant FLOAT frame on options - name already in use
// WARNING : [arnold] cannot declare constant FLOAT fps on options - name already in use`

**Comment by JenusL** [comment]
So I just put up #7 which fixes the frame and fps warning and adds some new features including Adaptive AA.
I don't get why the optix_denoiser.dll warning exists because the DLL is in the correct folder. Will open a Issue about that.
With PR 4, 5, 6 and 7 I consider the main work for Arnold 5.1.0 done. Now it's just adding new features as we see fit.

**Comment by JenusL** [comment]
So with 5.1.0.0 "support" done....
What new features should be added? What's realistic to pull of?
I know AOV Shaders have already been discussed on mailing list and there's a ticket in the trac so that should be pretty easy to add. Would be nice if more people would chime in and create issues of features they would like to be added.

**Comment by sjannuz** [comment]
Right, AOV shaders were the main request. The consensus seemed to be to abuse the output shaders port.
For denoising, I would wait a few weeks, to see if core simplifies the workflows.
Biggest things missing are the alembic procedural and the operators, the latter needing some thinking.

**Comment by sjannuz** [comment]
The render control API should not conflict with any of the other features. However, for now we have not included it in the other plugins, mostly for not having had the time to test it thoroughly.

**Comment by JenusL** [comment]
I created separate tickets for Arnold 5.1 features that hasn't been worked on yet.
So I think we can close this one now.

**Comment by caron** [comment]
Closing issue so we can track 5.1 and 5.2 features one by one
